audit_header: false
title: Philadelphia Real Estate Video Blog with Tandra & Jeremy Bowers
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET --
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Events
    url: 'https://suburblivingblog.com/events/'
  - title: Testimonials
    url: /testimonials/
  - title: Refer a Friend
    url: /referafriend/
client:
  name: Tandra & Jeremy Bowers
  title:
  license_number:
  about_markdown: >
    Since 2005, Tandra and her husband have been investing in real estate
    properties together, which has now afforded her the ability to focus solely
    on real estate as her Full-Time career. She brings to her clients a wealth
    of experience in sales and negotiation skills as well as thorough analysis
    in finding and securing the right property for them. She is a FULL-TIME
    licensed real estate agent who is enthusiastic, professional, and friendly.
  market: Philadelphia
  brand: Home Experts For You Real Estate Team
  brokerage: Keller Williams
  address: 901 Fayette St, 2nd FL <br/> Conshohocken, PA 19428

  phone: 215-680-4652
  phone_type:
  phone2:
  phone2_type:
  email: Tandra@homeexpertsforyou.com
  url:
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.homeexpertsforyou.com/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: /homevalue/
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: >-
      Find a home in Montgomery County, Bucks County, Delaware County, Chester
      County & Philadelphia
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://www.homeexpertsforyou.com/'
lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path:
  logo_path: /img/lender-logo.png
  name: Megan Munley
  license_number: NMLS 1352319
  title: Loan Officer
  brand: 2250 Hickory Road Suite 100 Plymouth Meeting, PA 19462
  phone: 215-833-7064
  phone_type: direct
  phone2: 215-618-8805
  phone2_type: office
  email: megan.byrne@fairwaymc.com
  url: 
socials:
  review_sm_icons: true
  facebook_url: 'https://www.facebook.com/Suburb-Living-by-Tandra-Bowers-462105017282729/'
  linkedin_url: 'https://www.linkedin.com/in/tandra-bowers-8a899126/'
  youtube_url: 'https://www.youtube.com/channel/UCr4R19fVVZrfTFnBZ6XV9tA'
  twitter_url: 'https://twitter.com/bowers_tandra'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Tandra-Bowers/'
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /uploads/tandra-logo.png
  logo_width_number: 50
  hero_text: Tandra's Real Estate Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /uploads/tandra-bowers-background-1.png
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#d11142'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#eeeeee'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'